[keyboard]
bindings = [
    { key = "Escape", mods = "Shift", action = "ToggleViMode"},
    { key = "Return", mods = "Alt|Shift", action = "CreateNewWindow" },
    { key = "Q", mods = "Alt", action = "Quit" },
]

[font]
size = 12.5

[general]
working_directory = "C:\\Users\\Min"

[window]
dimensions = { columns = 103, lines = 50 }
dynamic_padding = true
dynamic_title = true
position = { x=2, y=5 }
padding = { x=6, y=6 }
decorations = "Full"
decorations_theme_variant = "Dark"

[terminal]
shell = { program = "powershell", args = ["/nologo"] }

[debug]
render_timer = true
